project:
  type: website
  output-dir: docs

website:
  title: "Marcus Harris"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: profile.qmd
        text: Profile
      - href: essays.qmd
        text: Essays
      - href: research.qmd
        text: Research
      - href: cv.qmd
        text: CV
    right:
      - href: assets/CV.pdf
        text: CV (PDF)

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    toc: true
    code-copy: true
